Feature/test training
wolox-training/lmr-java pull request #13
Opened 2020-10-30 19:49 UTC by luismiguel0529

## Summary
- Test Book Controller
- Test User Controller
- Test User Dao 
- Test Book Dao
## Trello Card
https://trello.com/c/mNbyy49Y/28-junit-testing

2020-11-02 13:13 UTC, facucompe requested changes

2020-11-02 13:13 UTC, facucompe commented on src/test/java/wolox/training/repositories/BookRepositoryTest.java
> +        assertEquals(oneTestBook.getAuthor(), oneTestBook.getAuthor());
This is redundant. Use a findById to check the book is updated

2020-11-02 13:13 UTC, facucompe commented on src/test/java/wolox/training/repositories/UserRepositoryTest.java
> +        assertEquals(oneTestUser.getName(), persistedUser.getName());
Same here

2020-11-02 13:13 UTC, facucompe commented on src/test/java/wolox/training/util/TestEntities.java
> +        oneTestUser.setId(1l);
Don't set the Id

2020-11-03 12:17 UTC, joredudiaz reviewed
😄 a couple comments

2020-11-03 12:17 UTC, joredudiaz commented on src/main/java/wolox/training/controllers/UsersController.java
> +
Can remove this break line please?

2020-11-03 12:17 UTC, joredudiaz commented on src/test/java/wolox/training/controllers/BookControllerTest.java
> +    void whenUpdateBookThenReturnStatusCreated() throws Exception {
Can you test please when update a book that does not exists and returns not found?

2020-11-03 12:17 UTC, joredudiaz commented on src/test/java/wolox/training/controllers/BookControllerTest.java
> +    void whenDeleteBookThenReturnStatusNoContent() throws Exception {
Can you test please when delete a book that does not exists and returns not found?

2020-11-03 12:17 UTC, joredudiaz commented on src/test/java/wolox/training/controllers/UserControllerTest.java
> +    private UsersRepository mockUsersRepository;
Can you add a break line please?

2020-11-03 12:17 UTC, joredudiaz commented on src/test/java/wolox/training/controllers/UserControllerTest.java
> +
Can you remove this break line please?

2020-11-03 12:17 UTC, joredudiaz commented on src/test/java/wolox/training/controllers/UserControllerTest.java
> +    void whenUpdateUserThenReturnStatusCreated() throws Exception {
Can you test please when update an user that does not exists and returns not found?

2020-11-03 12:17 UTC, joredudiaz commented on src/test/java/wolox/training/controllers/UserControllerTest.java
> +    void whenFindAllUserTHenReturnStatusOK() throws Exception {
`whenFindAllUserThenReturnStatusOK`

2020-11-03 12:17 UTC, joredudiaz commented on src/test/java/wolox/training/controllers/UserControllerTest.java
> +    void whenDeleteUserThenReturnStatusNoContent() throws Exception {
Can you test please when delete an user that does not exists and returns not found?

2020-11-03 12:17 UTC, joredudiaz commented on src/test/java/wolox/training/controllers/BookControllerTest.java
> +    void whenFindAllBookTHenReturnStatusOK() throws Exception {
`whenFindAllBookThenReturnStatusOK`

2020-11-03 12:17 UTC, joredudiaz commented on src/test/java/wolox/training/repositories/BookRepositoryTest.java
> +    void whenCallFindALlBookThenReturnAllList() {
`whenCallFindAllBookThenReturnAllList`

2020-11-03 12:17 UTC, joredudiaz commented on src/test/java/wolox/training/repositories/UserRepositoryTest.java
> +    void whenCallFindALlUserThenReturnAllList() {
`whenCallFindAllUserThenReturnAllList`

2020-11-03 14:31 UTC, facucompe approved these changes

2020-11-03 14:32 UTC, facucompe approved these changes

2020-11-03 16:06 UTC, joredudiaz approved these changes

2020-11-03 16:07 UTC, merged