Feature/authenticated user information
wolox-training/lmr-java pull request #16
Opened 2020-11-02 17:15 UTC by luismiguel0529

## Summary
- Add method to view authenticated user
- Add Interface Authentication
## Trello Card
https://trello.com/c/6pWO41yc/27-acceder-a-la-informaci%C3%B3n-del-user-logueado

2020-11-03 12:37 UTC, joredudiaz submitted a review, later dismissed

2020-11-04 17:08 UTC, facucompe requested changes

2020-11-04 17:08 UTC, facucompe commented on src/main/java/wolox/training/controllers/UsersController.java
> +    public ResponseEntity<String> authUsername() {
Return a JSON. Not a Plain string

2020-11-04 17:08 UTC, facucompe commented on src/main/java/wolox/training/controllers/UsersController.java
> +    public ResponseEntity<String> authUsername() {
Create an object, or return a User

2020-11-04 17:37 UTC, luismiguel0529 commented on src/main/java/wolox/training/controllers/UsersController.java
> +    public ResponseEntity<String> authUsername() {
corrected please validate

2020-11-04 17:37 UTC, luismiguel0529 commented
corrected please validate

2020-11-04 20:40 UTC, facucompe approved these changes

2020-11-05 12:07 UTC, joredudiaz approved these changes

2020-11-05 13:11 UTC, merged