Feature/creation crud methods
wolox-training/lmr-java pull request #5
Opened 2020-10-26 20:47 UTC by luismiguel0529

## Summary
- Add Crud Book
- Add exception control
- Edit Entity Book
## Trello Card
https://trello.com/c/e89B0v13/18-crear-las-operaciones-crud-de-book

2020-10-26 21:20 UTC, facucompe requested changes
Great work!!

2020-10-26 21:20 UTC, facucompe commented on src/main/java/wolox/training/exception/RestExceptionHandler.java
> +
Extra line jumps
```suggestion
```

2020-10-26 21:20 UTC, facucompe commented on src/main/java/wolox/training/exception/BookNotFoundException.java
> +//@ResponseStatus(code = HttpStatus.NOT_FOUND,reason = "Book not found")
Remove commented code

2020-10-26 21:20 UTC, facucompe commented on src/main/java/wolox/training/controllers/BookController.java
> +    @PostMapping("/")
Just leave
```suggestion
    @PostMapping
```

2020-10-26 21:20 UTC, facucompe commented on src/main/java/wolox/training/controllers/BookController.java
> +    @GetMapping("/")
Same here:
```suggestion
    @GetMapping
```

2020-10-26 21:34 UTC, facucompe commented on src/main/java/wolox/training/controllers/BookController.java
> +    public Book findById(@PathVariable Long id) throws BookNotFoundException {
I prefer unchecked exceptions. Leave it if you want

2020-10-27 12:07 UTC, joredudiaz approved these changes
Good work! 😄

2020-10-27 18:43 UTC, facucompe approved these changes

2020-10-27 18:45 UTC, merged