Add javadoc in the project
wolox-training/lmr-java pull request #7
Opened 2020-10-27 14:11 UTC by luismiguel0529

## Summary

Comments are specifically added for the books functionality

- Add comment in the file Book Controller,BookRepository,Entity Book
- Add aditional comment in the file RestExceptionHandle ,UserRepository
- Finished PR structure
## Trello Card
https://trello.com/c/jG3dfwYL/47-javadoc

2020-10-27 17:04 UTC, joredudiaz commented on src/main/java/wolox/training/controllers/BookController.java
> +/***
son solo dos asteriscos (*) es decir `/**`

2020-10-27 17:06 UTC, joredudiaz commented on src/main/java/wolox/training/controllers/BookController.java
> + * Book controller containing the operations of update , find , delete , find by id and create
puedes darle un salto de linea adicional por favor para separar la descripción y el @author

2020-10-27 17:08 UTC, joredudiaz commented on src/main/java/wolox/training/controllers/BookController.java
> +     * Method for find all elements
puedes darle un salto de linea adicional por favor para separar la descripción y el `@return`

2020-10-27 17:08 UTC, joredudiaz commented on src/main/java/wolox/training/controllers/BookController.java
> +     * Method for search elements
puedes darle un salto de linea adicional por favor para separar la descripción y el `@return`

2020-10-27 17:09 UTC, joredudiaz commented on src/main/java/wolox/training/controllers/BookController.java
> +     * @return :returns all elements in BD
puedes dejarlo sin `:` en returns

2020-10-27 17:09 UTC, joredudiaz commented on src/main/java/wolox/training/controllers/BookController.java
> +     * @param id:variable used to identify the element to search
`id variable used to identify the element to search`

2020-10-27 17:12 UTC, joredudiaz commented on src/main/java/wolox/training/controllers/BookController.java
> +     * @return
te falto describir el return

2020-10-27 17:20 UTC, joredudiaz requested changes
😄 buen trabajo, un par de cositas no mas

2020-10-27 19:19 UTC, joredudiaz submitted a review, later dismissed
perfecto! 😄

2020-10-27 22:02 UTC, facucompe approved these changes, later dismissed

2020-10-28 15:38 UTC, joredudiaz approved these changes

2020-10-28 16:48 UTC, facucompe approved these changes

2020-10-28 16:52 UTC, merged