user controller is added, imports are optimized and a new exception i…
wolox-training/lmr-java pull request #8
Opened 2020-10-27 14:56 UTC by luismiguel0529

## Summary
- Add file UserController
- Imports are optimized
- Add new exception in file RestExceptionHandle
## Trello Card
https://trello.com/c/6AmB5jUG/21-crear-user-controller-con-las-operaciones-crud-de-user

2020-10-27 17:18 UTC, joredudiaz commented on src/main/java/wolox/training/controllers/UsersController.java
> +public class UsersController {
Puedes colocarle por favor aqui a todos los metodos y la clase los Javadoc

2020-10-27 17:20 UTC, joredudiaz requested changes
Solo te vi eso 😄

2020-10-27 18:54 UTC, facucompe approved these changes, later dismissed

2020-10-27 19:18 UTC, joredudiaz approved these changes, later dismissed
👌 excelente!

2020-10-28 17:18 UTC, joredudiaz approved these changes

2020-10-28 17:19 UTC, facucompe approved these changes

2020-10-28 17:32 UTC, merged