Feature/creation entity users
wolox-training/lmr-java pull request #9
Opened 2020-10-27 19:31 UTC by luismiguel0529

## Summary
- Add method in entity remove and add Books
- Add anotation Many to Many
- Delete empty
## Trello Card
https://trello.com/c/LjkkzQEQ/19-crear-modelo-de-user

2020-10-27 20:36 UTC, facucompe requested changes

2020-10-27 20:36 UTC, facucompe commented on src/main/java/wolox/training/models/Book.java
> +    public Book(Long id, String genre, @NotEmpty String author, @NotEmpty String image, @NotEmpty String title, @NotEmpty String subtitle, @NotEmpty String publisher, @NotEmpty String year, @NotEmpty
Annotations in params are enough

2020-10-27 20:36 UTC, facucompe commented on src/main/java/wolox/training/models/Users.java
> +    public Users(Long id, @NotEmpty String username, @NotEmpty String name, @NotEmpty LocalDate birthdate, @NotEmpty List<Book> books) {
Same here

2020-10-27 22:01 UTC, facucompe submitted a review, later dismissed

2020-10-28 12:15 UTC, joredudiaz commented on src/main/java/wolox/training/models/Users.java
> +    @Column(nullable = false)
This annotation is not necessary, because a user can not have books in loan

2020-10-28 12:15 UTC, joredudiaz commented on src/main/java/wolox/training/models/Users.java
> +    @NotEmpty
same with this annotation

2020-10-28 14:31 UTC, facucompe approved these changes

2020-10-28 14:35 UTC, joredudiaz approved these changes

2020-10-28 14:37 UTC, merged